### ISSUE TITLE
App crashes on Android 12 devices

### ISSUE THREAD

**Issue by dgurney75** [Pushwoosh/pushwoosh-adobe-air#28] opened 2022-08-30 15:00 UTC
I had a user test on her Android 12 device  and the app crashed on startup. It came back with a message stating that the app closed because it had a bug. I then ran it through the Android studio emulator and here is the logcat errors it returned. I don't have an Android 12 device, so i can't run the app on a device right now.

2022-08-30 10:49:01.913 9950-9979/air.com.maritz.lexusEnCompass E/FA: Missing google_app_id. Firebase Analytics disabled. See https://goo.gl/NAOOOI
2022-08-30 10:49:01.913 9950-9979/air.com.maritz.lexusEnCompass E/FA: Uploading is not possible. App measurement disabled
2022-08-30 10:49:01.933 9950-9988/air.com.maritz.lexusEnCompass E/AndroidRuntime: FATAL EXCEPTION: pool-7-thread-1
    Process: air.com.maritz.lexusEnCompass, PID: 9950
    java.lang.IllegalArgumentException: air.com.maritz.lexusEnCompass: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
        at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:645)
        at android.app.PendingIntent.getBroadcast(PendingIntent.java:632)
        at androidx.work.impl.utils.ForceStopRunnable.getPendingIntent(ForceStopRunnable.java:273)
        at androidx.work.impl.utils.ForceStopRunnable.isForceStopped(ForceStopRunnable.java:151)
        at androidx.work.impl.utils.ForceStopRunnable.forceStopRunnable(ForceStopRunnable.java:171)
        at androidx.work.impl.utils.ForceStopRunnable.run(ForceStopRunnable.java:102)
        at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)
2022-08-30 10:49:02.491 9950-9950/air.com.maritz.lexusEnCompass E/BufferQueueProducer: [SurfaceView[air.com.maritz.lexusEnCompass/air.com.maritz.lexusEnCompass.AIRAppEntry]#3(BLAST Consumer)3](id:26de00000003,api:0,p:-1,c:9950) disconnect: not connected (req=2)
2022-08-30 10:49:04.118 9950-9979/air.com.maritz.lexusEnCompass E/FA: Missing google_app_id. Firebase Analytics disabled. See https://goo.gl/NAOOOI

**Comment by dgurney75** [comment] 2022-08-30 16:02
Here's the full log: https://drive.google.com/file/d/1J813dOpCV280LAN0REWN2GALsSCmIk8S/view?usp=sharing

**Comment by wfhm** [comment] 2022-08-31 06:42
@dgurney75 checking it.

**Comment by dgurney75** [comment] 2022-09-06 16:37
Any update on this?

**Comment by wfhm** [comment] 2022-09-07 14:11
@dgurney75 I could not reproduce the issue on the latest ANE. The error itself indicates that somewhere in the Java code there are **PendingIntent**s that are created without adding mutability flags. Pushwoosh SDK was updated prior to Android 12 release specifically to address this issue, and PendingIntents are not created anywhere in the ANE code, so this most likely comes from dependencies. We expect to release the new ANE version in the nearest future to support latest Android 13 features, so all the dependencies will be updated accordingly. I will additionally update this thread when the new version is available or if we find the source of your issue in the meantime.

**Comment by marchbold** [comment] 2022-09-08 00:15
@dgurney75 Make sure you are using the latest androidx dependencies. This could be due to an old version of the libs.

**Comment by wfhm** [comment] 2022-09-08 11:07
@dgurney75 got it reproduced, will be fixed with the next release.

**Comment by dgurney75** [comment] 2022-09-08 16:30
Any idea when that will be? I need to get the app updated soon for he Android 12 requirement Google is mandating.

**Comment by wfhm** [comment] 2022-09-09 11:31
@dgurney75 I believe we can do it by the end of the day or early next week.

**Comment by wfhm** [comment] 2022-09-12 13:04
@dgurney75 fixed in 6.1.0. We've updated all Distriqt dependencies as well as added a couple of new ones, and the integration has slightly changed. Please refer to the changelog for additional details.

**Closed by wfhm** 2022-09-12 13:04 UTC
Labels: 72193
